language: csharp
solution: MonoGameSample.sln
install:
  # MonoGame 3.6
  - sudo apt-get install gtk-sharp3
  - wget http://www.monogame.net/releases/v3.6/monogame-sdk.run  
  # Extract contents and overwrite postinstall.sh to not prompt for input
  # See: https://github.com/MonoGame/MonoGame/issues/5879
  - chmod +x monogame-sdk.run
  - sudo ./monogame-sdk.run --noexec --keep --target ./monogame
  - sudo chmod 777 ./monogame/postinstall.sh
  - sed -i 's/read -p \"Continue (Y, n): \" choice2/choice2=\"Y\"/g' "./monogame/postinstall.sh"
  - cd monogame
  - sudo chmod +x postinstall.sh
  - sudo ./postinstall.sh
  - cd ..  
  - nuget restore
script:
  - msbuild
